commands:
  - name: start
    command: /start
    description: Выводит стартовое сообщение
    handler: InfoHandler
    admin: false
    visible: true
  - name: hello
    command: /hello
    description: Выводит приветствие
    handler: InfoHandler
    admin: false
    visible: true
  - name: help
    command: /help
    description: Список доступных комманд
    handler: InfoHandler
    admin: false
    visible: true
  - name: info
    command: /info
    description: Выводит информацию о боте
    handler: InfoHandler
    admin: false
    visible: true
  - name: test_events
    command: /test_events
    description: Запускает набор тестовых внутренних ивентов
    handler: TestEventHandler
    admin: true
    visible: true
  - name: subscribe
    command: /subscribe
    description: Подписаться на рассылку
    handler: SubscribeHandler
    admin: false
    visible: true
  - name: unsubscribe
    command: /unsubscribe
    description: Отписаться от рассылки
    handler: UnsubscribeHandler
    admin: false
    visible: true
  - name: sub_list
    command: /sub_list
    description: Список подписчиков
    handler: GetSubscribersListHandler
    admin: true
    visible: true
  - name: sub_count
    command: /sub_count
    description: Колличество подписчиков
    handler: GetSubscribersCountHandler
    admin: true
    visible: true